package cpu

type operationFn func() uint8
type addressModeFn func() uint8

type instruction struct {
	name    string
	op      operationFn
	addr    addressModeFn
	nCycles uint8
}

func setOpCodeLookups(cpu *Cpu) {
	illegal := instruction{"???", cpu.Illegal, cpu.ImpliedAddr, 1}

	cpu.opCodeLookup = [256]instruction{
		// 0x00-0x0F
		{"BRK", cpu.Brk, cpu.ImpliedAddr, 7},
		{"ORA", cpu.Ora, cpu.IndexedIndirectAddr, 6},
		illegal,
		illegal,
		illegal,
		{"ORA", cpu.Ora, cpu.ZeroPageAddr, 3},
		{"ASL", cpu.Asl, cpu.ZeroPageAddr, 5},
		illegal,
		{"PHP", cpu.Php, cpu.ImpliedAddr, 3},
		{"ORA", cpu.Ora, cpu.ImmAddr, 2},
		{"ASL", cpu.Asl, cpu.Accum, 2},
		illegal,
		illegal,
		{"ORA", cpu.Ora, cpu.AbsAddr, 4},
		{"ASL", cpu.Asl, cpu.AbsAddr, 6},
		illegal,
		// 0x10-0x1F
		{"BPL", cpu.Bpl, cpu.RelativeAddr, 2},
		{"ORA", cpu.Ora, cpu.IndirectIndexedAddr, 5},
		illegal,
		illegal,
		illegal,
		{"ORA", cpu.Ora, cpu.IndexedZeroPageAddrX, 4},
		{"ASL", cpu.Asl, cpu.IndexedZeroPageAddrX, 6},
		illegal,
		{"CLC", cpu.Clc, cpu.ImpliedAddr, 2},
		{"ORA", cpu.Ora, cpu.IndexedAbsAddrY, 4},
		illegal,
		illegal,
		illegal,
		{"ORA", cpu.Ora, cpu.IndexedAbsAddrX, 4},
		{"ASL", cpu.Asl, cpu.IndexedAbsAddrX, 7},
		illegal,
		// 0x20-0x2F
		{"JSR", cpu.Jsr, cpu.AbsAddr, 6},
		{"AND", cpu.And, cpu.IndexedIndirectAddr, 6},
		illegal,
		illegal,
		{"BIT", cpu.Bit, cpu.ZeroPageAddr, 3},
		{"AND", cpu.And, cpu.ZeroPageAddr, 3},
		{"ROL", cpu.Rol, cpu.ZeroPageAddr, 5},
		illegal,
		{"PLP", cpu.Plp, cpu.ImpliedAddr, 4},
		{"AND", cpu.And, cpu.ImmAddr, 2},
		{"ROL", cpu.Rol, cpu.Accum, 2},
		illegal,
		{"BIT", cpu.Bit, cpu.AbsAddr, 4},
		{"AND", cpu.And, cpu.AbsAddr, 4},
		{"ROL", cpu.Rol, cpu.AbsAddr, 6},
		illegal,
		// 0x30-0x3F
		{"BMI", cpu.Bmi, cpu.RelativeAddr, 2},
		{"AND", cpu.And, cpu.IndirectIndexedAddr, 5},
		illegal,
		illegal,
		illegal,
		{"AND", cpu.And, cpu.IndexedZeroPageAddrX, 4},
		{"ROL", cpu.Rol, cpu.IndexedZeroPageAddrX, 6},
		illegal,
		{"SEC", cpu.Sec, cpu.ImpliedAddr, 2},
		{"AND", cpu.And, cpu.IndexedAbsAddrY, 4},
		illegal,
		illegal,
		illegal,
		{"AND", cpu.And, cpu.IndexedAbsAddrX, 4},
		{"ROL", cpu.Rol, cpu.IndexedAbsAddrX, 7},
		illegal,
		// 0x40-0x4F
		{"RTI", cpu.Rti, cpu.ImpliedAddr, 6},
		{"EOR", cpu.Eor, cpu.IndexedIndirectAddr, 6},
		illegal,
		illegal,
		illegal,
		{"EOR", cpu.Eor, cpu.ZeroPageAddr, 3},
		{"LSR", cpu.Lsr, cpu.ZeroPageAddr, 5},
		illegal,
		{"PHA", cpu.Pha, cpu.ImpliedAddr, 3},
		{"EOR", cpu.Eor, cpu.ImmAddr, 2},
		{"LSR", cpu.Lsr, cpu.Accum, 2},
		illegal,
		{"JMP", cpu.Jmp, cpu.AbsAddr, 3},
		{"EOR", cpu.Eor, cpu.AbsAddr, 4},
		{"LSR", cpu.Lsr, cpu.AbsAddr, 6},
		illegal,
		// 0x50-0x5F
		{"BVC", cpu.Bvc, cpu.RelativeAddr, 2},
		{"EOR", cpu.Eor, cpu.IndirectIndexedAddr, 5},
		illegal,
		illegal,
		illegal,
		{"EOR", cpu.Eor, cpu.IndexedZeroPageAddrX, 4},
		{"LSR", cpu.Lsr, cpu.IndexedZeroPageAddrX, 6},
		illegal,
		{"CLI", cpu.Cli, cpu.ImpliedAddr, 2},
		{"EOR", cpu.Eor, cpu.IndexedAbsAddrY, 4},
		illegal,
		illegal,
		illegal,
		{"EOR", cpu.Eor, cpu.IndexedAbsAddrX, 4},
		{"LSR", cpu.Lsr, cpu.IndexedAbsAddrX, 7},
		illegal,
		// 0x60-0x6F
		{"RTS", cpu.Rts, cpu.ImpliedAddr, 6},
		{"ADC", cpu.Adc, cpu.IndexedIndirectAddr, 6},
		illegal,
		illegal,
		illegal,
		{"ADC", cpu.Adc, cpu.ZeroPageAddr, 3},
		{"ROR", cpu.Ror, cpu.ZeroPageAddr, 5},
		illegal,
		{"PLA", cpu.Pla, cpu.ImpliedAddr, 4},
		{"ADC", cpu.Adc, cpu.ImmAddr, 2},
		{"ROR", cpu.Ror, cpu.Accum, 2},
		illegal,
		{"JMP", cpu.Jmp, cpu.AbsIndirectAddr, 5},
		{"ADC", cpu.Adc, cpu.AbsAddr, 4},
		{"ROR", cpu.Ror, cpu.AbsAddr, 6},
		illegal,
		// 0x70-0x7F
		{"BVS", cpu.Bvs, cpu.RelativeAddr, 2},
		{"ADC", cpu.Adc, cpu.IndirectIndexedAddr, 5},
		illegal,
		illegal,
		illegal,
		{"ADC", cpu.Adc, cpu.IndexedZeroPageAddrX, 4},
		{"ROR", cpu.Ror, cpu.IndexedZeroPageAddrX, 6},
		illegal,
		{"SEI", cpu.Sei, cpu.ImpliedAddr, 2},
		{"ADC", cpu.Adc, cpu.IndexedAbsAddrY, 4},
		illegal,
		illegal,
		illegal,
		{"ADC", cpu.Adc, cpu.IndexedAbsAddrX, 4},
		{"ROR", cpu.Ror, cpu.IndexedAbsAddrX, 7},
		illegal,
		// 0x80-0x8F
		illegal,
		{"STA", cpu.Sta, cpu.IndexedIndirectAddr, 6},
		illegal,
		illegal,
		{"STY", cpu.Sty, cpu.ZeroPageAddr, 3},
		{"STA", cpu.Sta, cpu.ZeroPageAddr, 3},
		{"STX", cpu.Stx, cpu.ZeroPageAddr, 3},
		illegal,
		{"DEY", cpu.Dey, cpu.ImpliedAddr, 2},
		illegal,
		{"TXA", cpu.Txa, cpu.ImpliedAddr, 2},
		illegal,
		{"STY", cpu.Sty, cpu.AbsAddr, 4},
		{"STA", cpu.Sta, cpu.AbsAddr, 4},
		{"STX", cpu.Stx, cpu.AbsAddr, 4},
		illegal,
		// 0x90-0x9F
		{"BCC", cpu.Bcc, cpu.RelativeAddr, 2},
		{"STA", cpu.Sta, cpu.IndirectIndexedAddr, 6},
		illegal,
		illegal,
		{"STY", cpu.Sty, cpu.IndexedZeroPageAddrX, 4},
		{"STA", cpu.Sta, cpu.IndexedZeroPageAddrX, 4},
		{"STX", cpu.Stx, cpu.IndexedZeroPageAddrY, 4},
		illegal,
		{"TYA", cpu.Tya, cpu.ImpliedAddr, 2},
		{"STA", cpu.Sta, cpu.IndexedAbsAddrY, 5},
		{"TXS", cpu.Txs, cpu.ImpliedAddr, 2},
		illegal,
		illegal,
		{"STA", cpu.Sta, cpu.IndexedAbsAddrX, 5},
		illegal,
		illegal,
		// 0xA0-0xAF
		{"LDY", cpu.Ldy, cpu.ImmAddr, 2},
		{"LDA", cpu.Lda, cpu.IndexedIndirectAddr, 6},
		{"LDX", cpu.Ldx, cpu.ImmAddr, 2},
		illegal,
		{"LDY", cpu.Ldy, cpu.ZeroPageAddr, 3},
		{"LDA", cpu.Lda, cpu.ZeroPageAddr, 3},
		{"LDX", cpu.Ldx, cpu.ZeroPageAddr, 3},
		illegal,
		{"TAY", cpu.Tay, cpu.ImpliedAddr, 2},
		{"LDA", cpu.Lda, cpu.ImmAddr, 2},
		{"TAX", cpu.Tax, cpu.ImpliedAddr, 2},
		illegal,
		{"LDY", cpu.Ldy, cpu.AbsAddr, 4},
		{"LDA", cpu.Lda, cpu.AbsAddr, 4},
		{"LDX", cpu.Ldx, cpu.AbsAddr, 4},
		illegal,
		// 0xB0-0xBF
		{"BCS", cpu.Bcs, cpu.RelativeAddr, 2},
		{"LDA", cpu.Lda, cpu.IndirectIndexedAddr, 5},
		illegal,
		illegal,
		{"LDY", cpu.Ldy, cpu.IndexedZeroPageAddrX, 4},
		{"LDA", cpu.Lda, cpu.IndexedZeroPageAddrX, 4},
		{"LDX", cpu.Ldx, cpu.IndexedZeroPageAddrY, 4},
		illegal,
		{"CLV", cpu.Clv, cpu.ImpliedAddr, 2},
		{"LDA", cpu.Lda, cpu.IndexedAbsAddrY, 4},
		{"TSX", cpu.Tsx, cpu.ImpliedAddr, 2},
		illegal,
		{"LDY", cpu.Ldy, cpu.IndexedAbsAddrX, 4},
		{"LDA", cpu.Lda, cpu.IndexedAbsAddrX, 4},
		{"LDX", cpu.Ldx, cpu.IndexedAbsAddrY, 4},
		illegal,
		// 0xC0-0xCF
		{"CPY", cpu.Cpy, cpu.ImmAddr, 2},
		{"CMP", cpu.Cmp, cpu.IndexedIndirectAddr, 6},
		illegal,
		illegal,
		{"CPY", cpu.Cpy, cpu.ZeroPageAddr, 3},
		{"CMP", cpu.Cmp, cpu.ZeroPageAddr, 3},
		{"DEC", cpu.Dec, cpu.ZeroPageAddr, 5},
		illegal,
		{"INY", cpu.Iny, cpu.ImpliedAddr, 2},
		{"CMP", cpu.Cmp, cpu.ImmAddr, 2},
		{"DEX", cpu.Dex, cpu.ImpliedAddr, 2},
		illegal,
		{"CPY", cpu.Cpy, cpu.AbsAddr, 4},
		{"CMP", cpu.Cmp, cpu.AbsAddr, 4},
		{"DEC", cpu.Dec, cpu.AbsAddr, 6},
		illegal,
		// 0xD0-0xDF
		{"BNE", cpu.Bne, cpu.RelativeAddr, 2},
		{"CMP", cpu.Cmp, cpu.IndirectIndexedAddr, 5},
		illegal,
		illegal,
		illegal,
		{"CMP", cpu.Cmp, cpu.IndexedZeroPageAddrX, 4},
		{"DEC", cpu.Dec, cpu.IndexedZeroPageAddrX, 6},
		illegal,
		{"CLD", cpu.Cld, cpu.ImpliedAddr, 2},
		{"CMP", cpu.Cmp, cpu.IndexedAbsAddrY, 4},
		illegal,
		illegal,
		illegal,
		{"CMP", cpu.Cmp, cpu.IndexedAbsAddrX, 4},
		{"DEC", cpu.Dec, cpu.IndexedAbsAddrX, 7},
		illegal,
		// 0xE0-0xEF
		{"CPX", cpu.Cpx, cpu.ImmAddr, 2},
		{"SBC", cpu.Sbc, cpu.IndexedIndirectAddr, 6},
		illegal,
		illegal,
		{"CPX", cpu.Cpx, cpu.ZeroPageAddr, 3},
		{"SBC", cpu.Sbc, cpu.ZeroPageAddr, 3},
		{"INC", cpu.Inc, cpu.ZeroPageAddr, 5},
		illegal,
		{"INX", cpu.Inx, cpu.ImpliedAddr, 2},
		{"SBC", cpu.Sbc, cpu.ImmAddr, 2},
		{"NOP", cpu.Nop, cpu.ImpliedAddr, 2},
		illegal,
		{"CPX", cpu.Cpx, cpu.AbsAddr, 4},
		{"SBC", cpu.Sbc, cpu.AbsAddr, 4},
		{"INC", cpu.Inc, cpu.AbsAddr, 6},
		illegal,
		// 0xF0-0xFF
		{"BEQ", cpu.Beq, cpu.RelativeAddr, 2},
		{"SBC", cpu.Sbc, cpu.IndirectIndexedAddr, 5},
		illegal,
		illegal,
		illegal,
		{"SBC", cpu.Sbc, cpu.IndexedZeroPageAddrX, 4},
		{"INC", cpu.Inc, cpu.IndexedZeroPageAddrX, 6},
		illegal,
		{"SED", cpu.Sed, cpu.ImpliedAddr, 2},
		{"SBC", cpu.Sbc, cpu.IndexedAbsAddrY, 4},
		illegal,
		illegal,
		illegal,
		{"SBC", cpu.Sbc, cpu.IndexedAbsAddrX, 4},
		{"INC", cpu.Inc, cpu.IndexedAbsAddrX, 7},
		illegal,
	}

}
