package cpu

type operationFn func() uint8
type addressModeFn func() uint8

type instruction struct {
	name    string
	op      operationFn
	addr    addressModeFn
	nCycles uint8
}

func setOpCodeLookups(cpu *Cpu) {
	illegal := instruction{"???", cpu.illegal, cpu.impliedAddr, 2}

	cpu.opCodeLookup = [256]instruction{
		// 0x00-0x0F
		{"BRK", cpu.brk, cpu.impliedAddr, 7},
		{"ORA", cpu.ora, cpu.indexedIndirectAddr, 6},
		illegal,
		illegal,
		illegal,
		{"ORA", cpu.ora, cpu.zeroPageAddr, 3},
		{"ASL", cpu.asl, cpu.zeroPageAddr, 5},
		illegal,
		{"PHP", cpu.php, cpu.impliedAddr, 3},
		{"ORA", cpu.ora, cpu.immAddr, 2},
		{"ASL", cpu.asl, cpu.accumulator, 2},
		illegal,
		illegal,
		{"ORA", cpu.ora, cpu.absAddr, 4},
		{"ASL", cpu.asl, cpu.absAddr, 6},
		illegal,
		// 0x10-0x1F
		{"BPL", cpu.bpl, cpu.relAddr, 2},
		{"ORA", cpu.ora, cpu.indirectIndexedAddr, 5},
		illegal,
		illegal,
		illegal,
		{"ORA", cpu.ora, cpu.xIndexedZeroPageAddr, 4},
		{"ASL", cpu.asl, cpu.xIndexedZeroPageAddr, 6},
		illegal,
		{"CLC", cpu.clc, cpu.impliedAddr, 2},
		{"ORA", cpu.ora, cpu.yIndexedAbsAddr, 4},
		illegal,
		illegal,
		illegal,
		{"ORA", cpu.ora, cpu.xIndexedAbsAddr, 4},
		{"ASL", cpu.asl, cpu.xIndexedAbsAddr, 7},
		illegal,
		// 0x20-0x2F
		{"JSR", cpu.jsr, cpu.absAddr, 6},
		{"AND", cpu.and, cpu.indexedIndirectAddr, 6},
		illegal,
		illegal,
		{"BIT", cpu.bit, cpu.zeroPageAddr, 3},
		{"AND", cpu.and, cpu.zeroPageAddr, 3},
		{"ROL", cpu.rol, cpu.zeroPageAddr, 5},
		illegal,
		{"PLP", cpu.plp, cpu.impliedAddr, 4},
		{"AND", cpu.and, cpu.immAddr, 2},
		{"ROL", cpu.rol, cpu.accumulator, 2},
		illegal,
		{"BIT", cpu.bit, cpu.absAddr, 4},
		{"AND", cpu.and, cpu.absAddr, 4},
		{"ROL", cpu.rol, cpu.absAddr, 6},
		illegal,
		// 0x30-0x3F
		{"BMI", cpu.bmi, cpu.relAddr, 2},
		{"AND", cpu.and, cpu.indirectIndexedAddr, 5},
		illegal,
		illegal,
		illegal,
		{"AND", cpu.and, cpu.xIndexedZeroPageAddr, 4},
		{"ROL", cpu.rol, cpu.xIndexedZeroPageAddr, 6},
		illegal,
		{"SEC", cpu.sec, cpu.impliedAddr, 2},
		{"AND", cpu.and, cpu.yIndexedAbsAddr, 4},
		illegal,
		illegal,
		illegal,
		{"AND", cpu.and, cpu.xIndexedAbsAddr, 4},
		{"ROL", cpu.rol, cpu.xIndexedAbsAddr, 7},
		illegal,
		// 0x40-0x4F
		{"RTI", cpu.rti, cpu.impliedAddr, 6},
		{"EOR", cpu.eor, cpu.indexedIndirectAddr, 6},
		illegal,
		illegal,
		illegal,
		{"EOR", cpu.eor, cpu.zeroPageAddr, 3},
		{"LSR", cpu.lsr, cpu.zeroPageAddr, 5},
		illegal,
		{"PHA", cpu.pha, cpu.impliedAddr, 3},
		{"EOR", cpu.eor, cpu.immAddr, 2},
		{"LSR", cpu.lsr, cpu.accumulator, 2},
		illegal,
		{"JMP", cpu.jmp, cpu.absAddr, 3},
		{"EOR", cpu.eor, cpu.absAddr, 4},
		{"LSR", cpu.lsr, cpu.absAddr, 6},
		illegal,
		// 0x50-0x5F
		{"BVC", cpu.bvc, cpu.relAddr, 2},
		{"EOR", cpu.eor, cpu.indirectIndexedAddr, 5},
		illegal,
		illegal,
		illegal,
		{"EOR", cpu.eor, cpu.xIndexedZeroPageAddr, 4},
		{"LSR", cpu.lsr, cpu.xIndexedZeroPageAddr, 6},
		illegal,
		{"CLI", cpu.cli, cpu.impliedAddr, 2},
		{"EOR", cpu.eor, cpu.yIndexedAbsAddr, 4},
		illegal,
		illegal,
		illegal,
		{"EOR", cpu.eor, cpu.xIndexedAbsAddr, 4},
		{"LSR", cpu.lsr, cpu.xIndexedAbsAddr, 7},
		illegal,
		// 0x60-0x6F
		{"RTS", cpu.rts, cpu.impliedAddr, 6},
		{"ADC", cpu.adc, cpu.indexedIndirectAddr, 6},
		illegal,
		illegal,
		illegal,
		{"ADC", cpu.adc, cpu.zeroPageAddr, 3},
		{"ROR", cpu.ror, cpu.zeroPageAddr, 5},
		illegal,
		{"PLA", cpu.pla, cpu.impliedAddr, 4},
		{"ADC", cpu.adc, cpu.immAddr, 2},
		{"ROR", cpu.ror, cpu.accumulator, 2},
		illegal,
		{"JMP", cpu.jmp, cpu.absIndirectAddr, 5},
		{"ADC", cpu.adc, cpu.absAddr, 4},
		{"ROR", cpu.ror, cpu.absAddr, 6},
		illegal,
		// 0x70-0x7F
		{"BVS", cpu.bvs, cpu.relAddr, 2},
		{"ADC", cpu.adc, cpu.indirectIndexedAddr, 5},
		illegal,
		illegal,
		illegal,
		{"ADC", cpu.adc, cpu.xIndexedZeroPageAddr, 4},
		{"ROR", cpu.ror, cpu.xIndexedZeroPageAddr, 6},
		illegal,
		{"SEI", cpu.sei, cpu.impliedAddr, 2},
		{"ADC", cpu.adc, cpu.yIndexedAbsAddr, 4},
		illegal,
		illegal,
		illegal,
		{"ADC", cpu.adc, cpu.xIndexedAbsAddr, 4},
		{"ROR", cpu.ror, cpu.xIndexedAbsAddr, 7},
		illegal,
		// 0x80-0x8F
		illegal,
		{"STA", cpu.sta, cpu.indexedIndirectAddr, 6},
		illegal,
		illegal,
		{"STY", cpu.sty, cpu.zeroPageAddr, 3},
		{"STA", cpu.sta, cpu.zeroPageAddr, 3},
		{"STX", cpu.stx, cpu.zeroPageAddr, 3},
		illegal,
		{"DEY", cpu.dey, cpu.impliedAddr, 2},
		illegal,
		{"TXA", cpu.txa, cpu.impliedAddr, 2},
		illegal,
		{"STY", cpu.sty, cpu.absAddr, 4},
		{"STA", cpu.sta, cpu.absAddr, 4},
		{"STX", cpu.stx, cpu.absAddr, 4},
		illegal,
		// 0x90-0x9F
		{"BCC", cpu.bcc, cpu.relAddr, 2},
		{"STA", cpu.sta, cpu.indirectIndexedAddr, 6},
		illegal,
		illegal,
		{"STY", cpu.sty, cpu.xIndexedZeroPageAddr, 4},
		{"STA", cpu.sta, cpu.xIndexedZeroPageAddr, 4},
		{"STX", cpu.stx, cpu.yIndexedZeroPageAddr, 4},
		illegal,
		{"TYA", cpu.tya, cpu.impliedAddr, 2},
		{"STA", cpu.sta, cpu.yIndexedAbsAddr, 5},
		{"TXS", cpu.txs, cpu.impliedAddr, 2},
		illegal,
		illegal,
		{"STA", cpu.sta, cpu.xIndexedAbsAddr, 5},
		illegal,
		illegal,
		// 0xA0-0xAF
		{"LDY", cpu.ldy, cpu.immAddr, 2},
		{"LDA", cpu.lda, cpu.indexedIndirectAddr, 6},
		{"LDX", cpu.ldx, cpu.immAddr, 2},
		illegal,
		{"LDY", cpu.ldy, cpu.zeroPageAddr, 3},
		{"LDA", cpu.lda, cpu.zeroPageAddr, 3},
		{"LDX", cpu.ldx, cpu.zeroPageAddr, 3},
		illegal,
		{"TAY", cpu.tay, cpu.impliedAddr, 2},
		{"LDA", cpu.lda, cpu.immAddr, 2},
		{"TAX", cpu.tax, cpu.impliedAddr, 2},
		illegal,
		{"LDY", cpu.ldy, cpu.absAddr, 4},
		{"LDA", cpu.lda, cpu.absAddr, 4},
		{"LDX", cpu.ldx, cpu.absAddr, 4},
		illegal,
		// 0xB0-0xBF
		{"BCS", cpu.bcs, cpu.relAddr, 2},
		{"LDA", cpu.lda, cpu.indirectIndexedAddr, 5},
		illegal,
		illegal,
		{"LDY", cpu.ldy, cpu.xIndexedZeroPageAddr, 4},
		{"LDA", cpu.lda, cpu.xIndexedZeroPageAddr, 4},
		{"LDX", cpu.ldx, cpu.yIndexedZeroPageAddr, 4},
		illegal,
		{"CLV", cpu.clv, cpu.impliedAddr, 2},
		{"LDA", cpu.lda, cpu.yIndexedAbsAddr, 4},
		{"TSX", cpu.tsx, cpu.impliedAddr, 2},
		illegal,
		{"LDY", cpu.ldy, cpu.xIndexedAbsAddr, 4},
		{"LDA", cpu.lda, cpu.xIndexedAbsAddr, 4},
		{"LDX", cpu.ldx, cpu.yIndexedAbsAddr, 4},
		illegal,
		// 0xC0-0xCF
		{"CPY", cpu.cpy, cpu.immAddr, 2},
		{"CMP", cpu.cmp, cpu.indexedIndirectAddr, 6},
		illegal,
		illegal,
		{"CPY", cpu.cpy, cpu.zeroPageAddr, 3},
		{"CMP", cpu.cmp, cpu.zeroPageAddr, 3},
		{"DEC", cpu.dec, cpu.zeroPageAddr, 5},
		illegal,
		{"INY", cpu.iny, cpu.impliedAddr, 2},
		{"CMP", cpu.cmp, cpu.immAddr, 2},
		{"DEX", cpu.dex, cpu.impliedAddr, 2},
		illegal,
		{"CPY", cpu.cpy, cpu.absAddr, 4},
		{"CMP", cpu.cmp, cpu.absAddr, 4},
		{"DEC", cpu.dec, cpu.absAddr, 6},
		illegal,
		// 0xD0-0xDF
		{"BNE", cpu.bne, cpu.relAddr, 2},
		{"CMP", cpu.cmp, cpu.indirectIndexedAddr, 5},
		illegal,
		illegal,
		illegal,
		{"CMP", cpu.cmp, cpu.xIndexedZeroPageAddr, 4},
		{"DEC", cpu.dec, cpu.xIndexedZeroPageAddr, 6},
		illegal,
		{"CLD", cpu.cld, cpu.impliedAddr, 2},
		{"CMP", cpu.cmp, cpu.yIndexedAbsAddr, 4},
		illegal,
		illegal,
		illegal,
		{"CMP", cpu.cmp, cpu.xIndexedAbsAddr, 4},
		{"DEC", cpu.dec, cpu.xIndexedAbsAddr, 7},
		illegal,
		// 0xE0-0xEF
		{"CPX", cpu.cpx, cpu.immAddr, 2},
		{"SBC", cpu.sbc, cpu.indexedIndirectAddr, 6},
		illegal,
		illegal,
		{"CPX", cpu.cpx, cpu.zeroPageAddr, 3},
		{"SBC", cpu.sbc, cpu.zeroPageAddr, 3},
		{"INC", cpu.inc, cpu.zeroPageAddr, 5},
		illegal,
		{"INX", cpu.inx, cpu.impliedAddr, 2},
		{"SBC", cpu.sbc, cpu.immAddr, 2},
		{"NOP", cpu.nop, cpu.impliedAddr, 2},
		illegal,
		{"CPX", cpu.cpx, cpu.absAddr, 4},
		{"SBC", cpu.sbc, cpu.absAddr, 4},
		{"INC", cpu.inc, cpu.absAddr, 6},
		illegal,
		// 0xF0-0xFF
		{"BEQ", cpu.beq, cpu.relAddr, 2},
		{"SBC", cpu.sbc, cpu.indirectIndexedAddr, 5},
		illegal,
		illegal,
		illegal,
		{"SBC", cpu.sbc, cpu.xIndexedZeroPageAddr, 4},
		{"INC", cpu.inc, cpu.xIndexedZeroPageAddr, 6},
		illegal,
		{"SED", cpu.sed, cpu.impliedAddr, 2},
		{"SBC", cpu.sbc, cpu.yIndexedAbsAddr, 4},
		illegal,
		illegal,
		illegal,
		{"SBC", cpu.sbc, cpu.xIndexedAbsAddr, 4},
		{"INC", cpu.inc, cpu.xIndexedAbsAddr, 7},
		illegal,
	}

}
